### ISSUE TITLE
Use reMarked.js 

### ISSUE THREAD

**Issue by aziz** [JohnnyFee/CopyAsMarkdown#1]
Try using [reMarked.js ](https://github.com/leeoniya/reMarked.js) since it has some test coverage and a bit more extended support. like github code fences and even tables.

**Comment by JohnnyFee** [comment]
It sounds exciting! I'll have a try a bit later. Thanks very much.

**Comment by JohnnyFee** [comment]
I've changed to use reMark.js and publish a new release. It's really more powerful. Thanks.

**Comment by aziz** [comment]
Thanks for making this extension dude. :+1:
