### ISSUE TITLE
Expand relative links

### ISSUE THREAD

**Issue by jrunning** [JohnnyFee/CopyAsMarkdown#2]
Currently relative links aren't expanded, which makes them significantly less useful.

For example, this HTML from Wikipedia:

``` html
A MIME multipart message contains a <a href="/wiki/Delimiter#Content_boundary" title="Delimiter">boundary</a> in the "Content-Type: " header
```

...is copied as the following Markdown:

``` markdown
A MIME multipart message contains a [boundary](/wiki/Delimiter#Content_boundary "Delimiter") in the "Content-Type: " header
```

I can't paste this Markdown on another site without the link breaking. I would prefer for the link to be expanded, yielding this Markdown instead:

``` markdown
A MIME multipart message contains a [boundary](https://en.wikipedia.org/wiki/Delimiter#Content_boundary "Delimiter") in the "Content-Type: " header
```

**Comment by JohnnyFee** [comment]
Thank you for your suggestion. I will reproduce the bug and repair it in these days.

**Comment by JohnnyFee** [comment]
bug fixed
